version: '3.3'

services:

  nginx:
    image: nginx:1.17
    ports:
      - 8080:8080
    volumes:
      - ./app/public:/usr/src/app
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf

  mysql: 
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: sf4-docker
      MYSQL_PASSWORD: sf4-docker
      MYSQL_ROOT_DATABASE: sf4-docker
  
  adminer:
    image: adminer:latest
    ports:
      - 8081:8080