version: "3.7"
  services:

    nginx:
      image: nginx:1.17
      ports:
        - 8080:8080
      volumns:
        - ./app/public:/usr/src/app

    mysql: 
      image: mysql:8.0
      environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_ROOT_DATABASE: sf4-docker
    
    adminer:
      image: adminer: 4.7
      ports:
        - 8081:8080